metadata:
  labels:
    tags.datadoghq.com/env: "$DATADOG_ENV"
    tags.datadoghq.com/version: "${DATADOG_VERSION:0:42}"
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: "$DATADOG_ENV"
        tags.datadoghq.com/version: "${DATADOG_VERSION:0:42}"
      annotations:
        # language=JSON
        ad.datadoghq.com/$CONTAINER_NAME.tags: |
          {
            "git.commit.sha": "$COMMIT_SHA",
            "git.repository_url": "$REPOSITORY_URL"
          }
    spec:
      containers:
        - name: "$CONTAINER_NAME"
          image: "$DOCKER_IMAGE"
