metadata:
  labels:
    tags.datadoghq.com/env: "$DATADOG_ENV"
    tags.datadoghq.com/version: "$DATADOG_VERSION"
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: "$DATADOG_ENV"
        tags.datadoghq.com/version: "$DATADOG_VERSION"
    spec:
      containers:
        - name: "$CONTAINER_NAME"
          image: "$IMAGE_TAG"
